name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
        
      - name: Create build folder
        run: cmake . -B cmake-build-debug